### ISSUE TITLE
Add support for Race Schedule?

### ISSUE THREAD

**Issue by ianperrin** [iverly/f1-api#1]
Great work!

Any chance you could add support for the [Race Schedule](http://ergast.com/mrd/methods/schedule/)?

Thanks

**Comment by iverly** [comment]
Thanks !

Great idea, I will implement as soon as possible, probably tonight or tomorrow.

**Comment by iverly** [comment]
I just released v1.0.7 on npm (https://www.npmjs.com/package/f1-api/v/1.0.7) with the implementation of races scheduler.

Have fun @ianperrin 😉
