### ISSUE TITLE
Include Season and Round in ConstructorStandings and DriverStandings

### ISSUE THREAD

**Issue by ianperrin** [iverly/f1-api#2]
Hi

Thanks for implementing #1 ;)

Another request if I may...

The ErgastAPI for getting the Constructor and Driver Standings include the Season and Round

e.g.

````json
{
  "MRData": {
    "xmlns": "http://ergast.com/mrd/1.0",
    "series": "f1",
    "limit": "30",
    "offset": "0",
    "total": "22",
    "StandingsTable": [
      "season": "2008",
      "StandingsLists": [
        {
          "season": "2008",
          "round": "18",
          "DriverStandings": [
            .
            .
            .
          ]
        }
      ]
    }
  }
}
````

Would it be possible to include these in the respective methods within this package?

* getCurrentDriverStandings
* getDriverStandings
* getCurrentConstructorStandings
* getConstructorStandings

**Comment by iverly** [comment]
Hi ! 

I just released v1.1.0 on npm (https://www.npmjs.com/package/f1-api/v/1.107) with your request.

This release includes the new object StandingList:

```ts
export interface StandingList<T> {
    season: number;
    round: number;
    standings: T;
}
```

Have fun 😉
