### ISSUE TITLE
Support multiple constructors in driver standings

### ISSUE THREAD

**Issue by ianperrin** [iverly/f1-api#3]
Occasionally a driver will race for multiple constructors in one season, e.g.

* In [2016](http://ergast.com/api/f1/2016/driverStandings), Max Verstappen and Danii Kuyat both raced for multiple constructors
* In [2020](http://ergast.com/api/f1/2020/driverStandings), so did George Russell

In the current implementation, getDriverStandings (and getCurrentDriverStandings) returns the first constructor from the api.

Could the package be amended to return an array of Constructors?

**Comment by iverly** [comment]
Such a great idea !!! I completely forget about it :(

Just released on npm v1.2.0 with the implementation !

Have fun 😉
